// Generated by CoffeeScript 1.9.3
(function() {
  var CONTENT, button, clickable, dialog, setHoldTime, style, text, timer;

  if (document.getElementById('areyousure')) {
    return;
  }

  CONTENT = "<?xml version=\"1.0\"?>\n<svg id=\"areyousure-button\" viewBox=\"0 0 240 240\" version=\"1.1\"\n  xmlns=\"http://www.w3.org/2000/svg\">\n\n    <filter id=\"areyousure-dropshadow\" height=\"130%\">\n      <feGaussianBlur in=\"SourceAlpha\" stdDeviation=\"2\"/>\n      <feOffset dx=\"2\" dy=\"0\" result=\"offsetblur\"/>\n      <feComponentTransfer>\n        <feFuncA type=\"linear\" slope=\"0.5\"/>\n      </feComponentTransfer>\n      <feMerge>\n        <feMergeNode/>\n        <feMergeNode in=\"SourceGraphic\"/>\n      </feMerge>\n    </filter>\n\n    <circle id=\"areyousure-circle\" cx=\"120\" cy=\"120\" r=\"100\" style=\"filter:url(#areyousure-dropshadow)\"/>\n    <text id=\"areyousure-text\" x=\"120\" y=\"120\" font-size=\"24px\"\n        fill=\"white\" dominant-baseline=\"middle\" text-anchor=\"middle\">\n      Are you sure?\n    </text>\n</svg>";

  dialog = document.createElement('dialog');

  dialog.id = 'areyousure';

  dialog.innerHTML = CONTENT;

  document.children[0].appendChild(dialog);

  dialog.showModal();

  style = document.createElement('style');

  document.children[0].appendChild(style);

  setHoldTime = function(time) {
    var content;
    content = "#areyousure-button:active #areyousure-circle {\n  transition: stroke-dashoffset " + time + "s linear !important;\n}";
    return style.textContent = content;
  };

  timer = null;

  clickable = false;

  button = dialog.querySelector('#areyousure-button');

  text = dialog.querySelector('#areyousure-text');

  chrome.storage.sync.get('holdTime', function(result) {
    var holdTime;
    holdTime = result.holdTime || 2;
    setHoldTime(holdTime);
    button.addEventListener('mousedown', function(ev) {
      if (ev.button !== 0) {
        return;
      }
      return timer = setTimeout(function() {
        clickable = true;
        return button.classList.add('activated');
      }, holdTime * 1000);
    });
    button.addEventListener('mouseup', function() {
      clearTimeout(timer);
      return button.classList.remove('activated');
    });
    return button.addEventListener('click', function(e) {
      if (!clickable) {
        return;
      }
      text.textContent = '✔';
      button.classList.add('completed');
      dialog.close();
      dialog.remove();
      style.remove();
      return chrome.runtime.sendMessage("clicked");
    });
  });

}).call(this);
