// Generated by CoffeeScript 1.12.5
(function() {
  var CONTENT, button, completed, container, dialog, dynamicStyle, setStyles, shadow, staticStyle, text, timer;

  if (document.getElementById('areyousure')) {
    return;
  }

  CONTENT = "<button hidden>\n  <svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\"\n    viewBox=\"0 0 240 240\">\n\n      <filter id=\"areyousure-dropshadow\" height=\"130%\">\n        <feGaussianBlur in=\"SourceAlpha\" stdDeviation=\"2\"/>\n        <feOffset dx=\"2\" dy=\"0\" result=\"offsetblur\"/>\n        <feComponentTransfer>\n          <feFuncA type=\"linear\" slope=\"0.5\"/>\n        </feComponentTransfer>\n        <feMerge>\n          <feMergeNode/>\n          <feMergeNode in=\"SourceGraphic\"/>\n        </feMerge>\n      </filter>\n\n      <circle id=\"areyousure-circle\" cx=\"120\" cy=\"120\" r=\"100\" style=\"filter:url(#areyousure-dropshadow)\"/>\n      <text id=\"areyousure-text\" x=\"120\" y=\"120\" font-size=\"24px\"\n          fill=\"white\" dominant-baseline=\"middle\" text-anchor=\"middle\">\n        Are you sure?\n      </text>\n  </svg>\n</button>";

  container = document.createElement('div');

  shadow = container.attachShadow({
    mode: 'open'
  });

  shadow.resetStyleInheritance = true;

  dialog = document.createElement('dialog');

  dialog.style.background = 'none';

  dialog.style.border = 'none';

  shadow.appendChild(dialog);

  dialog.id = 'areyousure';

  dialog.innerHTML = CONTENT;

  dialog.addEventListener('cancel', function(e) {
    return e.preventDefault();
  });

  document.documentElement.appendChild(container);

  dialog.showModal();

  staticStyle = document.createElement('link');

  staticStyle.rel = 'stylesheet';

  staticStyle.type = 'text/css';

  staticStyle.href = chrome.runtime.getURL('content.css');

  shadow.appendChild(staticStyle);

  dynamicStyle = document.createElement('style');

  shadow.appendChild(dynamicStyle);

  setStyles = function(arg) {
    var backdropOpacity, content, holdTime;
    holdTime = arg.holdTime, backdropOpacity = arg.backdropOpacity;
    content = "#areyousure button:active circle {\n  transition: stroke-dashoffset " + holdTime + "s linear !important;\n}\n\n#areyousure::backdrop {\n  background-color: rgba(0,0,0," + backdropOpacity + ");\n}";
    return dynamicStyle.textContent = content;
  };

  timer = null;

  completed = false;

  button = dialog.querySelector('button');

  text = dialog.querySelector('text');

  chrome.storage.sync.get({
    holdTime: 2,
    backdropOpacity: 0.8
  }, function(opts) {
    var start, stop;
    setStyles(opts);
    start = function(ev) {
      if (!(ev.button === 0 || ev.code === 'Space')) {
        return;
      }
      if (timer || completed) {
        return;
      }
      return timer = setTimeout(function() {
        completed = true;
        return button.classList.add('completed');
      }, opts.holdTime * 1000);
    };
    stop = function(ev) {
      if (!(ev.button === 0 || ev.code === 'Space')) {
        return;
      }
      if (!timer) {
        return;
      }
      clearTimeout(timer);
      timer = null;
      return button.classList.remove('activated');
    };
    button.addEventListener('blur', function() {
      return button.focus();
    });
    button.addEventListener('mousedown', start);
    window.addEventListener('mouseup', stop);
    button.addEventListener('keydown', start);
    window.addEventListener('keyup', stop);
    return button.addEventListener('click', function(e) {
      if (!completed) {
        return e.preventDefault();
      }
      window.removeEventListener('mouseup', stop);
      window.removeEventListener('keyup', stop);
      dialog.close();
      container.remove();
      return chrome.runtime.sendMessage("clicked");
    });
  });

}).call(this);
