// Generated by CoffeeScript 1.9.1
(function() {
  var filter, listen, listener, unlisten;

  listener = function(ev) {
    chrome.tabs.update(ev.tabId, {
      url: "about:blank"
    });
    if (confirm("Are you sure you want to visit " + ev.url + " ?")) {
      chrome.tabs.update(ev.tabId, {
        url: ev.url
      });
      unlisten();
      return chrome.alarms.create({
        delayInMinutes: 5
      });
    }
  };

  filter = {
    url: [
      {
        hostSuffix: "reddit.com"
      }, {
        hostSuffix: "news.ycombinator.com"
      }
    ]
  };

  listen = function() {
    return chrome.webNavigation.onBeforeNavigate.addListener(listener, filter);
  };

  unlisten = function() {
    return chrome.webNavigation.onBeforeNavigate.removeListener(listener);
  };

  chrome.alarms.onAlarm.addListener(listen);

  listen();

}).call(this);
