// Generated by CoffeeScript 1.12.5
(function() {
  var $, catchError, storage;

  $ = document.querySelector.bind(document);

  storage = chrome.storage.sync;

  catchError = function(f) {
    return function() {
      if (chrome.runtime.lastError) {
        return alert(chrome.runtime.lastError.string);
      } else if (f) {
        return f.apply(this, arguments);
      }
    };
  };

  storage.get({
    sites: [],
    holdTime: 2,
    cooldown: 5,
    backdropOpacity: 0.8
  }, catchError(function(opts) {
    var site;
    $('#sites').value = ((function() {
      var i, len, ref, results;
      ref = opts.sites;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        site = ref[i];
        results.push(site.hostSuffix);
      }
      return results;
    })()).join('\n');
    $('#holdTime').value = opts.holdTime;
    $('#cooldown').value = opts.cooldown;
    return $('#dimming').value = Math.round(opts.backdropOpacity * 100);
  }));

  $('#sites').addEventListener('input', function() {
    var site, sites;
    sites = (function() {
      var i, len, ref, results;
      ref = $('#sites').value.split('\n');
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        site = ref[i];
        if (site) {
          results.push({
            hostSuffix: site
          });
        }
      }
      return results;
    })();
    return storage.set({
      sites: sites
    }, catchError());
  });

  $('#holdTime').addEventListener('input', function() {
    return storage.set({
      holdTime: parseFloat($('#holdTime').value)
    }, catchError());
  });

  $('#cooldown').addEventListener('input', function() {
    return storage.set({
      cooldown: parseFloat($('#cooldown').value)
    }, catchError());
  });

  $('#dimming').addEventListener('input', function() {
    return storage.set({
      backdropOpacity: parseFloat($('#dimming').value) / 100
    }, catchError());
  });

}).call(this);
